# Generated by Django 5.0.6 on 2024-06-10 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Имя не удовлетворяет требованиям', regex='^[А-ЯЁ][а-яё]* [А-ЯЁ][а-яё]* [А-ЯЁ][а-яё]*$')])),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Логин не удовлетворяет требованиям', regex='^(?!me$)[a-zA-Z0-9-]+$')])),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Телефон не удовлетворяет требованиям', regex='^\\+[\\d]+$')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('passport', models.ImageField(blank=True, null=True, upload_to='passport_images/')),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'volunteers',
            },
        ),
    ]
