services:
  db:
    image: postgres
    container_name: nakormi-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nakormi
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build: ./nakormi_back
    container_name: nakormi-api
    restart: always
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  bot:
    build: ./nakormi_bot
    container_name: nakormi-bot
    restart: always
    depends_on:
      db:
        condition: service_healthy