services:
  api:
    build: ./nakormi_back
    container_name: nakormi-api
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./nakormi_back/.env

  bot:
    build: ./nakormi_bot
    container_name: nakormi-bot
    restart: always
    env_file:
      - ./nakormi_bot/.env